#!/bin/bash

# Source my jenkins config if available
if [ -f ~/.jenkins.sh ]; then
  echo "SOURCING"
  . ~/.jenkins.sh
fi

# Source the ruby env ci settings
. ./scripts/ci_ruby_env

bundle install --without development

COVERALLS_REPO_TOKEN=qE2nIlN6JDk5KWWYfhzg6poChzAVTTZEn bundle exec spec
